Group1Web2/Models/ErrorViewModel.cs
namespace Group1Web2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Group1Web2/Models/Profesori.cs
namespace Group1Web2.Models
{
    public class Profesori
    {
        public Profesori(string emri,string mbiemri)
        {
            Emri=emri;
            Mbiemri=mbiemri;
        }
        public string Emri { get; set; }
        public string Mbiemri { get; set; }

    }
}

Group1Web2/Controllers/HomeController.cs
using Group1Web2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Group1Web2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Privaciteti()
        {
            return View();
        }
    }
}

Group1Web2/Controllers/ProfesorController.cs
using Group1Web2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Group1Web2.Controllers
{
    public class ProfesorController : Controller
    {
        public IActionResult Index()
        {
            Group1Web2.Models.Profesori prof1 = new Profesori("Leron", "Berisha");
            Profesori prof2 = new Profesori("Shkelqim", "Miftari");
            List<Profesori> profesoret = new List<Profesori>();
            profesoret.Add(prof1);
            profesoret.Add(prof2);
            return View(profesoret);
        }

        public IActionResult MesoHtml()
        {
            return View();
        }

    }
}

Group1Web2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Group1Web2/Views/Home/Privaciteti.cshtml
<h1>
    Privaciteti
</h1>

Group1Web2/Views/Profesor/Index.cshtml
@model List<Profesori>

Mire se vini profesor

@foreach (Profesori prof in @Model)
{
    <h1>@prof.Emri</h1>
}

Group1Web2/Views/Profesor/MesoHtml.cshtml
<style>
    #diviKryesor {
        background-color: green !important;
        font-family: Verdana;
        height: 200px;
    }

    .tjere {
        background-color: blue;
        color: white;
        opacity: 0.5;
    }
</style>

@*<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>
<h4>Heading 4</h4>
<h5>Heading 5</h5>
<h6>Heading 6</h6>
<p> Studente a jeni mire.</p>
<p> Studente a jeni mire.</p>
<p> Studente a jeni mire.</p>
<p> Studente a jeni mire.</p>
<p> Studente a jeni mire.</p>*@
<div style="padding: 20px; color: white; background-color: red; width: 200px; height: 100px;  border: 1px solid black;">
    Kastriot Gjoka
</div>
<p style="margin-top:0px ">
    Leron Berisha
</p>
<p>
    <label for="perdorusi">Perdorusi</label>
    <input id="perdorusi" type="text"/>
</p>
<p><input type="email" /></p>
<p><input type="file" /><p>
<form method="post">
    <div>
        <label for="perdorusi1">Perdoruesi</label>
        <input id="perdorusi1" type="text"/>
    </div>
    <div>
        <label for="pass">Fjalekalimi</label>
        <input id="pass" type="password"/>
    </div>
    <div>
        <input type="submit" class="btn btn-success" value="Dergo" id="submit"/>
    </div>
</form>

<div id="diviKryesor">
    Permbajtja e divit kryesor
</div>

<div class="tjere">
    AAA
</div>

<div class="tjere">
    BBBB
</div>

<a href="https://aab-edu.net/">Kolegji AAB</a>
<a asp-controller="Profesor" asp-action="Index" >Profesoret</a>

Group1Web2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Group1Web2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Group1Web2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Group1Web2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Faqja krysore</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profesor" asp-action="Index">Profesoret</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Home" asp-action="Privaciteti">Privaciteti</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Group1Web2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>